name: Build and Export Artifact

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Build app
        run: xcodebuild -scheme 7DayNutritionReportApp -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Archive app
        run: |
          xcodebuild -scheme 7DayNutritionReportApp -sdk iphoneos -configuration Release archive -archivePath ${{github.workspace}}/build/7DayNutritionReportApp.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Export .ipa
        run: |
          xcodebuild -exportArchive -archivePath ${{github.workspace}}/build/7DayNutritionReportApp.xcarchive -exportPath ${{github.workspace}}/build -exportOptionsPlist ExportOptions.plist
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 7DayNutritionReportApp
          path: build/*.ipa 